ITRS-Group/monitor-ninja

modules/lsfilter/src/js/LSFilterInputWindow.js
Listview on hover comment-icon, title attribute "Comments" covers some of the
information of the comment.
Removed title attribute on comment-icon hover.
This fixes MON-11538
Signed-off-by: Ramesh T ramesht@op5.com
=> Tooltip issue in comment on hover fixed

modules/lsfilter/src/js/LSFilterInputWindow.js
Previously title attribute was removed for all icon's in listview on hover.
Now we removed title attribute only for comment icon on hover.
This fixes MON-11538
Signed-off-by: Ramesh T ramesht@op5.com
=> Remove title attribute for comment-icon on hover

modules/lsfilter/src/js/LSFilterList.js
This commit ensures that when nachos banner is not shown the margin at top won't be too wide at dashboard.
This fixes MON-11558
Signed-off by: Adrián Villalba <avillalba@itrsgroup.com>
=> Fix too wide margin at top when nachos banner is not shown

modules/monitoring/includes/downtime.php, test/DowntimeWeekTest.php, test/includes/downtime.php
With the new format, items are always contained in a sequential array, example:
[{"day": x}]
The old format does not use sequential arrays for single items, example:
{"day": x}
This will make pluck_recurrence() compatible with both.
=> Make pluck_recurrence compatible with the legacy recurrence_on format

modules/monitoring/views/recurring_downtime/js/recurring_downtime.js
This will disable/not show the summary inside the recurring downtime item view.
=> Disable the recurring downtime summary

modules/lsfilter/src/js/LSFilterList.js
After Peter did the verification process, he found a better way to solve the problem.
This ensures that when nachos banner is not shown there won't be a too wide gap.
This fixes MON-11558
=> Fix too wide gap when nacho's banner is not shown

application/controllers/ajax.php
When $setting_info was an empty array, $setting_href would not be
initialized and then caused an undefined variable error later on.
This fixes MON-11594.
Signed-off-by: Petter Nyström <pnystrom@op5.com>
=> Fix undefined variable in validate_uri_string

application/media/css/lib.popover.css
Previously help text that is supposed to appear when hovering a round help icon, it was flicker so we can't read it.
Now flicker issue on help icon hover is fixed, able to read it.
This fixes MON-11518
Signed-off-by: Ramesh T ramesht@op5.com
=> Help text flicker when hovering a help icon fixed

modules/reports/models/scheduled_reports.php
MON-11611 Scheduled reports created before 8.0.2 are no longer generated
Earlier there was some problem in generating old reports due to
timezone.
we changed the sql query to check timezone and scheduled report .
=> MON-11611 Scheduled reports created before 8.0.2 are no longer generated

application/controllers/ajax.php
When $setting_info was an empty array, $setting_href would not be
initialized and then caused an undefined variable error later on.
This fixes MON-11594.
Signed-off-by: Petter Nyström <pnystrom@op5.com>
=> Fix undefined variable in validate_uri_string (#41)

application/views/css/form.css
This commit change the style of rights sentence in login page.
This ensures that the sentence is not bold.
This fixes MON-11361.
=> Change rights sentence style

application/views/css/layout.css
The product image in the menu had to much margin to the right. So that when you
hovered the image an area next right to the image became grey. With less right
margin this won't happen.
This is a part of MON-11626
Signed-off-by: Elin Linder <elinder@op5.com>
=> Decreased margin on product image in menu

modules/monitoring/models/naemonobject.php, modules/monitoring/views/monitoring/naemon_command.php
This commit reduce the number of alerts after multiaction.
This ensures that only a general alert will be displayed and not one alert for each host.
This fixes MON-11665.
=> Reduce scrolling after multiaction

application/views/css/form.css
This commit changes the CSS of the create admin account's form.
This ensures that the create admin account page matches with the rebranding.
This fixes MON-11674
=> Update create admin account

modules/monitoring/includes/datetime.php, test/DowntimeWeekTest.php
NinjaDateTime uses ISO 8691 to express dates and time, with week days
numbered as 1-7, 7 being Sunday. While the input data uses the North
American/Islamic system which numbers week days as 0-6, 0 being Sunday.
This caused recurring downtimes scheduled on a Sunday to fail, while all
other week days worked correctly. With this commit the function which
returns the day of the week is updated to use the 0-6 format.
Fixes: MON-11684
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
=> Apply recurring downtimes on Sundays

modules/monitoring/includes/datetime.php, test/DowntimeWeekTest.php
NinjaDateTime uses ISO 8691 to express dates and time, with week days
numbered as 1-7, 7 being Sunday. While the input data uses the North
American/Islamic system which numbers week days as 0-6, 0 being Sunday.
This caused recurring downtimes scheduled on a Sunday to fail, while all
other week days worked correctly. With this commit the function which
returns the day of the week is updated to use the 0-6 format.
Fixes: MON-11684
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
=> Apply recurring downtimes on Sundays (#81)

op5build/monitor-ninja.logrotate, op5build/monitor-ninja.spec
ninja logs and few files inside ninja folder
currently do not have any logrotate funtionality.
As a result the file grows rapidly over a period of time.
This fix addresses this issue by adding logrotate option.
MON-11668
Signed-off by:sbhapur@op5.com
=> ninja: Add logrotate funtionality

application/controllers/search.php, modules/monitoring/views/extinfo/components/operating.php, modules/monitoring/views/extinfo/css/extinfo.css
This commit rename "Operating status" label to "Runtime options" and add a tooltip next to it.
This ensures the user is guided to persistent configuration.
This fixes MON-11030.
=> Rename label to "Runtime options" and add tooltip

application/views/css/form.css
When creating the initial admin account in Monitor, this style
is used for a message telling the user that admin credentials
cannot be recovered.
This element should not have a static height, as this will cause
a message that is longer to overflow outside of the div.
Instead, no height should mean that the box to expands downwards
as more text is added.
This fixes: MON-11748
"Text overflow when creating admin account on fresh install"
=> Removing password-helper height declaration

application/views/css/layout.css
This ensures that reduce polling and load on Nachos API, Nachos banners has been removed from all pages, except the save configuration page. Banners have also been redesigned.
This fixes MON-11730.
=> Remove nachos banners

modules/menu/views/menu.php, modules/monitoring/hooks/listview_menu_hook.php
Earlier, the list of filters and dashboards to show has been very
limited. With this update the number of filters shown has been increased
to 15 filters, for hosts, services, hostgroups and servicegroups.
Also, to these menu options there has been added a filter title.
This fixes MON-11604
Signed-off-by: Elin Linder <elinder@op5.com>
=> Show more filters and dashboards in menu

features/support/configuration.rb, op5build/monitor-ninja.spec
As of Monitor 8, livestatus queries are made against LMD. To ensure all
integration tests works correct, we add LMD as a dependency to the
package.
=> Add LMD dependency

op5build/monitor-ninja.spec
As the issue with LMD not starting correctly, after LMD being installed,
should not be correct, we no longer need to start it manually here.
=> Do not start LMD manually

modules/reports/views/reports/header.php
Stop try to print time zone and state types for logger reports.
When doing a "log archive search" from the Logger listview, a report of
type "logger" is created, which shares report header code with other
report types. But for a logger report, some data, like the
`report_timezone` added in MON-11209 is not available which causes a
call to `timezone_utc_no()` to crash.
This fixes MON-11763.
=> Adapt report header for logger reports

modules/monitoring/models/downtime.php, modules/monitoring/models/naemonobject.php
To delete a downtime ninja would prior to this commit use the external
command DEL_HOST_DOWNTIME or DEL_SVC_DOWNTIME. However this would fail
to remove downtimes for peers and pollers iff the downtime was not yet
started.
This happens for two reasons:
1) Merlin cannot safely propagate DEL_HOST/SVC_DOWNTIME to other nodes
as this external command requires a downtime_id argument which is not
guaranteed to be the same on all nodes.
2) Instead Merlin relies on deleting downtimes when a
NEBATTR_DOWNTIME_STOP_CANCELLED event happens, which is propagated
across to all relevant nodes. However this event only occurs if a
downtime is deleted AFTER the downtime start time, and as a result it
would therefore be missed.
Instead we will use DEL_DOWNTIME_BY_HOST_NAME which we can safely
propagate to all …
=> Use DEL_DOWNTIME_BY_HOST_NAME to delete downtimes

modules/monitoring/models/downtime.php, modules/monitoring/models/naemonobject.php
To delete a downtime ninja would prior to this commit use the external
command DEL_HOST_DOWNTIME or DEL_SVC_DOWNTIME. However this would fail
to remove downtimes for peers and pollers iff the downtime was not yet
started.
This happens for two reasons:
1) Merlin cannot safely propagate DEL_HOST/SVC_DOWNTIME to other nodes
as this external command requires a downtime_id argument which is not
guaranteed to be the same on all nodes.
2) Instead Merlin relies on deleting downtimes when a
NEBATTR_DOWNTIME_STOP_CANCELLED event happens, which is propagated
across to all relevant nodes. However this event only occurs if a
downtime is deleted AFTER the downtime start time, and as a result it
would therefore be missed.
Instead we will use DEL_DOWNTIME_BY_HOST_NAME which we can safely
propagate to all …
=> Use DEL_DOWNTIME_BY_HOST_NAME to delete downtimes (7.5)

application/src/js/jquery.datePicker.js
If you click on the calendar picker from event log's report, weekdays
don't looks correctly. Also, a weird character is next to the year.
With this commit, those errors will be fixed. Each day of the week is
setted in the good way and the weird character has been removed.
This fixes MONUI-58
=> Datapicker broken in event log

op5build/ninja.httpd-conf, op5build/ninja.httpd-conf.el7
This commit enables gzip compression in the apache http web server.
According to the chrome developer audit tool, this change brings the
performance score for monitor in the browser from 1 to 32 points out of
a 100.
Fixes: MON-10630
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
=> Enable gzip compression

application/views/css/form.css, features/password.feature, features/step_definitions/mocked_configuration.rb, modules/auth/views/login.php
The size of the login button is too small. Also, the text is not well
written.
If applied, this commit will change the size and the text.
This fixes MONUI-80
=> Change login button's size and text

modules/reports/models/scheduled_reports.php
This is a major re-write of the get_period_schedules() function, that
had some faults in it, causing report to not be sent or sent on the
wrong days.
This implementation should be more robust, since it doesn't rely on that
the system clock is exactly the same as the scheduled reports selected
report time.
However, this change doesn't claim to be a perfect solution to
scheduling reports.
Daily scheduled reports
-----------------------
With this change daily scheduled reports are generated as soon as
current time is beyond one report period after the report was previously
sent.
Example schedule:
- Daily report using timezone UTC
- Report time is 12:00 (same timezone as report)
- Scheduled to be sent every 2nd day
If the report was last sent anytime at 2019-10-15, it will be sent
first thing …
=> Re-write cron function to get periodic schedules

modules/reports/models/scheduled_reports.php
This fixes a bug where if a report is scheduled weekly on multiple days,
it was sent every time the code ran on the subsequent scheduled days,
since `last_sent` wasn't updated. With this change, `last_sent` updates
every time a weekly schedule is sending the report.
And improve a couple of readability things.
This fixes MON-11823.
=> Fix weekly scheduled reports on multiple days

modules/reports/models/scheduled_reports.php
This fixes a bug where if a report is scheduled weekly on multiple days,
it was sent every time the code ran on the subsequent scheduled days,
since `last_sent` wasn't updated. With this change, `last_sent` updates
every time a weekly schedule is sending the report.
And improve a couple of readability things.
This fixes MON-11823.
(cherry picked from commit a073ae92aa16fc0dbb50834d4fe4a42a8468681c)
=> Fix weekly scheduled reports on multiple days 7.5

application/views/css/layout.css, application/views/template.php
If LMD or Livestatus are down only a message saying "Page has no content"
is shown. This is not too much information for the user.
If this commit is applied, the user will know which service is not running.
This fixes MONUI-76
=> Add message info when LMD or Livestatus are down

application/views/css/form.css
Due to the size of the button in the login page has been increased, the
size of the button in the registration page has to be increased as well.
This fixes MONUI-91
=> Increase button size in registration page

modules/menu/hooks/menu_main_hook.php
If LMD is not running, manage in menu has an incorrect margin top.
With this commit, the margin top will be the correct.
This fixes MONUI-107
=> Fix manage in menu margin top

application/controllers/search.php
The tooltip for runtime options in the extinfo page is not correct since
the settings stay after restart.
If applied, this commit will change the text.
This fixes MONUI-132
=> Change tooltip text in extinfo page

modules/reports/controllers/schedule.php, modules/reports/models/scheduled_reports.php
With this patch we will not assume that there is a 'report_timezone'
report option stored, which is the case for reports that were saved
before the 'report_timezone' option was introduced.
Log to Ninja log on notice level (not enabled by default) when sending
reports, so that it can be tracked easier whether we're trying to send
reports when scheduled or not.
This fixes MON-11912.
=> Fix report schedules for reports with missing timezone

modules/monitoring/models/host.php, modules/monitoring/models/service.php
These descriptions are visible when acknowledging the state of
an object in the UI, through the extinfo page or via the drop-down.
1) When using a checkbox in a UI, it's implicit that leaving that
box checked is a "yes" answer to the text provided, so there is no
need to say "If you want ... check this checkbox". This change
makes the descriptions shorter and hopefully more clear.
2) On customer request, we have added a note that if the object is
in a scheduled downtime, the acknowledgement notification will be
sent regardless. This is maybe not intuitive or obvious, but it's
the way it is so the text should probably underline this fact.
This fixes MONUI-155
=> Clarify description text for commands

modules/monitoring/models/host.php, modules/monitoring/models/naemonobject.php, modules/monitoring/models/service.php
For `del_downtime_by_host_name()`, send the Naemon external command
`DEL_DOWNTIME_BY_HOST_NAME`.
This is part of MON-11872.
=> Add del_downtime_by_host_name to host/service models

modules/monitoring/models/naemonobject.php
0182856827d205a459fb78eb5996043930ec447d introduced a regression making
it the external command for downtime deletion incorrect for downtime
objects. With this commit we ensure that the correct keys are using in
all scenarios.
This fixes: MON-11978
=> Correct downtime deletion on downtime objects

modules/monitoring/models/host.php, modules/monitoring/models/service.php
Previously, all downtimes were deleted by using the
DEL_HOST/SVC_DOWNTIME external command. However this was changed in
937db15e27c413da00d7564744a386227307b556 to use `DEL_DOWNTIME_BY_HOSTNAME`
instead.
This, seemed to have caused a regression for deleting all downtimes of a
host/service.
This commit the downtimes can be deleted correctly when calling the
cancel all function.
Fixes: MON-12040
=> Fix deletion of all downtimes

modules/monitoring/models/host.php, modules/monitoring/models/service.php
Previously, all downtimes were deleted by using the
DEL_HOST/SVC_DOWNTIME external command. However this was changed in
937db15e27c413da00d7564744a386227307b556 to use `DEL_DOWNTIME_BY_HOSTNAME`
instead.
This, seemed to have caused a regression for deleting all downtimes of a
host/service.
This commit the downtimes can be deleted correctly when calling the
cancel all function.
Fixes: MON-12040
=> Fix deletion of all downtimes (7.5)

op5build/ninja.httpd-conf
Partly revert of 94721c0b1adba56faf0dd9502e034ba3863f9231
Fixes MON-12022.
=> Disable apache gzip compression for EL6 (maint/7.5)

modules/monitoring/models/host.php, modules/monitoring/models/service.php
Following adding the option to delete downtimes via the API, an unwanted
side effect occured, where we got a new "Delete Downtime" option in
listviews. This did not work, causing confusing.
It appears as though it is not possible to hide this action from the
listviews, without affecting the API. This commit therefore fixes the
view so that the command can be sent successfully via the GUI.
This fixes: MON-12088
=> Fix delete downtime by hostname action in GUI

modules/monitoring/models/host.php, modules/monitoring/models/service.php
Following adding the option to delete downtimes via the API, an unwanted
side effect occured, where we got a new "Delete Downtime" option in
listviews. This did not work, causing confusing.
It appears as though it is not possible to hide this action from the
listviews, without affecting the API. This commit therefore fixes the
view so that the command can be sent successfully via the GUI.
This fixes: MON-12088
=> Fix delete downtime by hostname action in GUI (7.5)

application/models/ninja_setting.php
For unknown reasons it seems like sometimes duplicate quicklinks can
occur. This commit is a workaround to that problem, by ensuring that
Ninja doesn't show these duplicates.
This fixes: MON-11765
=> Fix duplicate quicklinks

application/models/ninja_setting.php
In the previous commit: 925b87b duplicate quicklinks was fixed.
However in some cases the fix would not work. The reason for this was
that array_unique would leave index gaps in an indexed. That is you
could end up with an array like:
```
[0] => ...
[2] => ...
```
When then encoding the array with `json_encode`, the we would get an
indexed array like so:
`{"0":{quicklink}, "2":{quicklink}`
instead of the desired format:
`[{quicklink},{quicklink}]`
=> Fix double quicklins when indexes are out of order

features/schedule.feature, modules/reports/models/scheduled_reports.php, modules/reports/src/js/schedule.js, modules/reports/views/schedule/new_schedule.php
Add support for scheduling monthly reports on "the first day of month".
Change one of the schedule report test cases to use the new monthly
option.
This fixes MON-12098.
=> Add first day of month schedule option

features/schedule.feature, modules/reports/models/scheduled_reports.php, modules/reports/src/js/schedule.js, modules/reports/views/schedule/new_schedule.php
Add support for scheduling monthly reports on "the first day of month".
Change one of the schedule report test cases to use the new monthly
option.
This fixes MON-12419.
(cherry picked from commit 6b1a8774f0735c44acfa47ba06444180e1237aa4)
=> Add first day of month schedule option (maint/7.5)

application/languages/en/en.po, modules/reports/controllers/reports.php
Removes redundant text in a tool tip on the schedule reports page.
Signed-off-by: Daniel Nilsson <dnilsson@itrsgroup.com>
=> Remove redundant text in tool tip

features/support/configuration.rb, features/support/mock.rb
Due to an update of something Ruby related on CentOS generation of
tmp directories seems to have failed (missing slashes between prefix).
This commit should fix that by depending on `File.join` instead.
=> Fix tmpname generation

application/views/css/layout.css
This relative path to bg.png does not make sense in the
application/views/css directory which this file is in, because there is
no "images" directory here.
Anything using this CSS file will get a 404 error, as it
will try to request an image file that does not exist.
It seems that one of the components that actually use this "non-theme"
is the HTML that is rendered to go into a report via wkhtmltopdf, so you
can reproduce this 404 error by trying the following:
- Generate a PDF report from the GUI by clicking "As PDF" in the top
right corner.
- Grep for 404 in your /var/log/httpd/ssl_access_log and you will see
something like the following:
"GET /monitor/application/views/css/images/bg.png HTTP/1.1" 404 241
It's a problem because it causes wkhtmltopdf to exit with a non-zero
return code, …
=> Fix PNG path to avoid 404 errors

features/support/configuration.rb, features/support/mock.rb, modules/widgets/controllers/tac.php
This filters input/output on dashboard names for dangerous javascript.
The filter on the input is not needed as ModSec filters that correctly, but I have put it in as a failsafe if modsec is disabled.
If you somehow managed to get a dangerous name in the Merlin database the output filtering should avoid any javascript from executing
This fixes: MON-12468 which is part of the EMCA Pen tests (MON-12205)
I also included a fix done by Jacob Hansen that fixes the test-running.
Signed-off-by: Axel Bolle abolle@itrsgroup.com
=> Xss in dashboard names 7.5

modules/widgets/controllers/tac.php
This filters input/output on dashboard names for dangerous javascript.
The filter on the input is not needed as ModSec filters that correctly, but I have put it in as a failsafe if modsec is disabled.
If you somehow managed to get a dangerous name in the Merlin database the output filtering should avoid any javascript from executing
This fixes: MON-12468 which is part of the EMCA Pen tests (MON-12205)
=> Filter both input and output on dashboard names

modules/reports/controllers/base_reports.php
The current behavior is that on failure, STDOUT is debug-logged, which
is bad because STDOUT from wkhtmltopdf is normally a binary blob which
we put into a PDF file. My assumption is that we only care about the
return code and STDERR, we don't want binary stuff in ninja.log.
This change removes debug-logging of STDOUT, and enables debug-logging
of *all* HTML passed to wkhtmltopdf, even when it succeeds. The idea
here is that if you have enabled debug logging, you probably want as
much info as possible regarding what is being passed.
This can be tested by setting level:debug in log.yml, generating a PDF
report and then looking for "HTML:" in ninja.log
The "bug" here is that, for example, once you have written binary to
ninja.log, you can no longer grep this file without extra work.
=> Change behavior of wkhtmltopdf debug logging

modules/widgets/controllers/tac.php, modules/widgets/widgets/dead/dead.php
This will filter the input to the widgets to dissallow the adding of
dangerous javascript.
This will also filter the output of the widget error handling to prevent
the execution of dangerous javascript
This fixes MON-12469 which is part of the EMCA Pen tests (MON-12205)
=> Fix XSS in error msg on broken widget

src/op5/auth/Auth.php
On logout, destroy the $_SESSION and delete the session cookie that was
automatically created, using the recommended approach from php.net.
This fixes the issue that the session cookie (ninjasession) was not
deleted on logout.
Part of MON-12207.
=> Fix deletion of session cookie on logout

op5build/monitor-ninja.spec, test/ConfigTest.php
This changes the installation of ninja packages so that most files are
owned by root and thus are now writable by any user on the system.
This fixes a potential security problem where a malicious user could
overwrite for example a php file, using monitors write permissions.
=> Change owner of installed files to root

modules/form/src/js/form.js, modules/lsfilter/widgets/bignumber/bignumber.php, modules/widgets/src/js/jquery.easywidgets.js, modules/widgets/src/js/tac.js
This change sets the selected option value in widget menu-list (select item).
-Fixing english translation
-When pressing Save or Cancel on widget resets default hover title on cog icon (edit widget)
-If the user is editing the widgets title and the widget updates throu ajax the title field does not update
Part of MONUI-189
Signed-off-by: Erling Larsson
<elarsson@itrsgroup.com>
=> Pressing 'cancel' on widget settings resets the values

op5build/ci_config.yml
Builds started to fail due to errors when installing ruby gems.
Adding a specific version of the racc gem to be installed, 1.4.15
instead of the latest version 1.5.2 seemd to resolve the issue.
Signed-off-by: Daniel Nilsson <dnilsson@itrsgroup.com>
=> Add scpecific version of racc gem

features/monitoring_host.feature, modules/monitoring/views/extinfo/components/banners/children.php, modules/monitoring/views/extinfo/components/banners/membership.php, modules/monitoring/views/extinfo/components/banners/parents.php, modules/monitoring/views/extinfo/components/statebox.php, op5build/ci_config.yml
This commit adds two new views that displays on extinfo if there are
parents or children for the current object. According to Naemon,
services can have parents too, but I can't find this in the GUI so I
guess we only support it for hosts.
In addition, it modifies the behavior of the membership view (box) to
conform with the new behavior of these two new views: 3 or more are
shown, otherwise they are collapsed into one listview link.
This fixes MON-9844
=> Show parents and children in extinfo view

modules/auth/views/401.php, modules/menu/views/about.php, modules/reports/controllers/alert_history.php
These are left over references to op5.com which no longer serves a web
site, so I have replaced the links with the ITRS equivalents.
I have also removed the link on the logo in the about popup, since the
exact same link is right below it.
=> Remove references to op5.com

application/controllers/ajax.php
With MON-11283 we started escaping reserved HTML characters in quicklink
URIs, which introduced the issue that it was no longer possible to use
ampersand characters (&) in the URI as they would be escaped (&amp;).
This is bad because it essentially disables the use of query parameters
in quicklinks, something that we frequently use within Monitor itself.
Additionally the escaping happened on both saving and loading of the
data, resulting in double escaped data. And because all quicklinks were
saved together, the more quicklinks you added the more escaped would the
older quicklinks get... In short, a mess.
This commit tries to address the problem by removing the escaping of
HTML characters. We try to maintain the protection against XSS attacks
(which the changes in MON-11283 was targeting) …
=> Stop HTML escaping quicklink URI

src/op5/auth/AuthDriver_Keycloak.php
This commit cleans up the AuthDriver_Keycloak class. We make a concious
decision to include Keycloak users in the local user data stored on
file. We do this to simplify the implementation of the other methods
expected in the AuthDriver API, which are also implemented with this
commit (basically copy pasted from the Default driver, with the
exception that we only look at Keycloak users).
With this commit we also create Keycloak users that does not already
exist as local users. This relies on Keycloak including the "grp" claim
that includes the group memberships the user should be created with.
This is part of MON-12654.
=> Complete AuthDriver_Keycloak API and create new users

features/step_definitions/status.rb
The trigger method is not supported with the Selenium driver so we use
the hover method instead.
This only seems to affect the tests for `monitor-op5reports`.
=> Replace use of Capybara::Node::Element.trigger

features/step_definitions/status.rb, src/op5/auth/AuthDriver_Default.php
- Replace use of Capybara::Node::Element.trigger: This fixes a problem in the op5reports tests.
- Use password_verify: This is not related to op5reports but resolves a password issue I discovered while troubleshooting.
See commit messages for details.
=> Fix legacy password handling on PHP 7

modules/reports/controllers/schedule.php
This fixes the "send report now" action for scheduled reports, where
ninja/Kohana dies with exception due to the PHP warning:
count(): Parameter must be an array or an object that implements Countable
Fixes MON-12833.
=> Fix invalid use of count() for string length

modules/auth/controllers/auth.php, modules/reports/models/scheduled_reports.php
* Prevent login from redirecting to unknown sites
The login page allows us to set a `uri` query parameter to an address
where the user will be redirected after a successful login (or directly
redirected if already logged in). This commit limits this feature to
only work for pages on the same site. Attempts at redirecting to a
different site will instead be redirected to the default start page.
This type of open redirects could be used in phishing attacks, so it's
safer to disallow it. There doesn't appear to be any use cases in
Monitor that would warrant a redirect outside the site, afaict.
If we wanted to be even more rigid we could probably implement this type
of check in the `redirect` helper function itself, but then the impact
becomes much broader and it might break some valid use …
=> Fix reported vulnerabilities

application/languages/en/en.po, modules/lsfilter/controllers/listview.php
There was some confusion around the column config option `all`, and why
it didn't return more columns than the `default` option. This updates
the tooltip to instead refer to `default`, which also matches the
documentation.
It appears that `all` will return the same set of columns as `default`,
which are all those that are defined in the file
modules/monitoring/src/js/lsfilter_renderer_table.js.
This is part of MON-12901.
=> Update tooltip for listview column config

application/views/css/layout.css, application/views/icons/mui-account-icon.svg, application/views/profile.php, application/views/template_header.php, modules/auth/models/user.php
With this commit the use of Gravatar will be disabled in Monitor 9,
and we use a material UI icon instead.
This is a part of MON-9437
=> MON-9473: Disable Gravatar

application/views/css/layout.css
Earlier changes to button design, as a part of Monitor 9, also affected the confirmation box.
With this commit it is once again blue, as it should be.
This fixes MONUI-890
=> MONUI-890: Confirmation box should be blue

application/media/css/jquery.filterable.css
After earlier updates, for Monitor 9, the filterable move buttons became invisible and out of place.
With this update we add color to it and put it back in it's place.
This fixes MONUI-888
=> MONUI-888: Styling issues for filterable move buttons

modules/test/libraries/MockAuth.php, src/op5/auth/Auth.php, system/libraries/Session.php, test/AuthDriverDefaultTest.php, test/AuthTest.php, test/bootstrap.php
Upon successful login, generate a new session id and destroy the old
session. This increases protection against session hijacking.
The patch is largely based on "Example #2 Avoiding lost session by
session_regenerate_id()" at
https://www.php.net/manual/en/function.session-regenerate-id.php
A related change is that we will deploy php configuration on the system
that sets `session.use_strict_mode=1` elsewhere, as that is required for
secure session management.
Fixes MON-12480.
=> Re-generate session id on login

modules/auth/views/login.php
Previously there was a resizing of the logo on the login page.
It is not needed anymore.
This is a part of MONUI-902
=> MONUI-902: Remove resize product image

application/controllers/user.php
Since php 7 we can no longer count() objects to find out if they are populated.
!empty() is used instead.
=> Changing theme crashes ninja

application/views/css/form.css, modules/auth/views/login.php
ITRS don't own the full copyright, as ninja is based on the Kohana
framework. Remove notice.
This fixes: MON-12975
=> Remove ITRS copyright notice on login screen

modules/monitoring/views/extinfo/components/host_states.php
The host states links on the extinfo page for hostgroups were broken.
They were trying to filter on 'host.groups' rather than just 'groups'.
This resulted in a lsfilter query like this:
[hosts] host in "<hostgroup_name>" ...
Which results in a 500 error because 'host' is not a recognized field.
This commit changes the links to just 'groups', which makes them work as
expected. It does not address the 500 error, however, because the
efforts involved proved insurmountable by the author.
This is part of MON-12830.
=> Fix host states links

op5build/ninja-httpd.conf
With the removal of the OP5 Portal in Monitor 9, we don't have any
landing page on the root path of the Monitor web server. This commit
adds a redirect from the the root web path to the Ninja site, which in
turn is redirected depending on whether there is an active session or
not. A new user browsing to the Monitor server will then typically come
to the Ninja login page instead.
This is part of MON-12622.
=> Redirect / to /monitor/index.php

modules/monitoring/src/js/backup.js
Click handler was not loaded at the proper time so it could not intercept the a tag redirect.
=> Fix document load order

features/backup.feature
Add a test case that does a backup & restore of configuration through
the UI.
This test would reproduce the problem in MON-12985, if monitor-http-api
were installed, which is not normally the case when this test suite
runs.
However, it should fail in case similar issues arise in the future,
where some file included in the backup is not writable by the
unprivileged user that runs restore (httpd process).
Part of MON-12985.
=> Add feature test for backup/restore config

modules/monitoring/controllers/backup.php
Ninjas backup/restore config feature should only backup files that are
written to by the config UI. As /etc/op5 contains files that are not
meant to be modified by users, even less by any UI, they should not be
backed up here.
Restore won't work with files owned by root either, and there are such
files in /etc/op5.
However, everything in /etc/op5 is included in the system level backup
created with the "op5-backup" CLI program.
Fixes MON-13019, MON-12985.
=> Only include specific /etc/op5 files in backup

modules/monitoring/controllers/backup.php
Ninjas backup/restore config feature should only backup files that are
written to by the config UI. As /etc/op5 contains files that are not
meant to be modified by users, even less by any UI, they should not be
backed up here.
Restore won't work with files owned by root either, and there are such
files in /etc/op5.
However, everything in /etc/op5 is included in the system level backup
created with the "op5-backup" CLI program.
Fixes MON-13019, MON-12985.
(cherry picked from commit c797a1a3fbf47074df091f625be5f5a21f76a37f)
=> Only include specific /etc/op5 files in backup (maint/8.x)

features/step_definitions/nagios.rb
No more flaky tests due to disabling of php-opcache in: https://github.com/ITRS-Group/system-addons-op5-httpd/pull/8
```
334 scenarios (334 passed)
4550 steps (4550 passed)
```
-----------------
This reverts commit 8dccd3d244233f5777691d1423fe0aeb60dfbb49.
It turns out the flaky tests was caused by dnf pulling in the weak
dependency `php-opcache` which wasn't installed on 7.2 before.
We've now disable php-opcache, hence this additional sleep should no
longer be needed.
Part of: MON-12965
=> Revert "Tests: add sleep between config file cp..

application/controllers/ajax.php
The purpose of validate_uri_string appears to be cleaning up href values
inside a list of JSON objects, but we are feeding this function all
sorts of values -- including non-JSON data. This commit makes the
validate_uri_string bail and return its argument unchanged, if it cannot
be parsed as a JSON list. This fixes a problem where the refresh rate on
listview pages could not be saved, because of an error in the mentioned
function.
=> Don't loop over non-arrays in validate_uri_string

modules/monitoring/src/js/pnp/pnp.js
Graphs on the PNP page has a button that lets us save it as the "default
graph". (It is unknown to me what being the default graph actually does,
though.) This functionality was broken since a recent update to
PNP4Nagios that changed the order in which the source and view query
parameters appear in the URL, which is then fixed by this commit. (This
is obviously a very fragile way of getting the data in the first place,
but I'm not going to bother doing more than necessary at this point.)
This is part of MON-13020.
=> Fix saving default graph from PNP page

application/config/database.php
This commit updates the Nacoma database config to use the utf8mb4
charset instead of latin1. Other relevant changes are in the Nacoma
repository, but the config of the database connection used needs to be
updated here.
This is part of MON-12319.
=> Update Nacoma database to UTF-8

application/src/js/application/common.js
The pause button was trying to get the .attr of a checkbox, this is no
longer valid in jquery3+ - changed to prop.
The popup for the successful saving of refresh inteval is moved to
execute when the post is successful and is now presenting the rouded value.
This solves: 
MON-13048
MON-13047
=> Fix broken listview update setting box

application/src/js/lib.popover.js, modules/monitoring/controllers/pnp.php, modules/monitoring/src/js/pnp/pnp.js
This will introduce a new behavior for the graph button in list views.
When you now hover over the graph icon in a list view a lookup will be done
to see if the setting "default_graph" is set on that particular host. If
set, it will display the corresponding graph from pnp.
Also changed the way we save default_graph in the database. It is now
stored as a single json object instead of 2 separate entries. This
halves database requests when looking them up, due to our ORM.
Implemented a getter for the default_graph value that is to be accessed
via ajax.
=> Make default graph actually do something

modules/monitoring/src/js/pnp/pnp.js
This fix should not be made on maint/8.x because the corresponding
changes on monitor-pnp has not happened on Monitor 8.
This is part of MON-13020.
This reverts commit 77f4f43e599ff4e24be852634f86a5a8a398e5c8.
=> Revert "Fix saving default graph from PNP page"

modules/monitoring/controllers/backup.php
The Backup/Restore feature in Ninja would only restore the configuration
files without touching the Nacoma database. This could result in Nacoma
not matching the actual configuration, if file changes are not detected.
With this commit we run the `undo_config` action in the Nacoma API as
part of the restore, which reloads the config in the database from the 
config files.
This is part of MON-13039.
=> Undo config after backup restore

src/op5/auth/Auth.php
* Log on notice level when a user is successfully logged in.
* Change log levels for failed authentication and authorization attemps
from debug to notice.
Fixes MON-13077.
=> Log successful login attempts

op5build/monitor-ninja.spec
* Explicitly specify php-cli dependency (on php 7.4, php-cli is only a
weak dependency of php).
* Allow the specfile to parse properly in the case where the systemd
macros have yet to be installed (RHEL8 mock builds).
=> op5build: Fix building on RHEL8

modules/monitoring/src/js/extinfo.js
.complete is deprecated and should not be used. Instead we should use
.always on post requests made by jquery.
This solves: MON-13133
=> Change .complete to .always when doing a post request

features/step_definitions/capybara.rb
We now handle time using localtime to account for timezones.
=> Fix dst handling in report tests

modules/reports/controllers/schedule.php
The fwrite("\n") seems to no longer be needed. As the PDFs look fine without it. And it was causing issues when using through the web-gui
This is part of: MON-13146
=> Reports send now functionality och allow saving to /tmp

modules/reports/src/js/lightbox_edit_settings.js
The event handler is added to the checkboxes after loading the dom.
=> Initiate event handlers on Lightbox load

modules/reports/src/js/lightbox_edit_settings.js
The event handler is added to the checkboxes after loading the dom.
=> Initiate event handlers when using Lightbox

modules/reports/models/scheduled_reports.php
The "last_sent" parameter is now being allowed to be set on the scheduled report entry in the database. 
This will fix the issue with Ninja emailing report recipients every minute.
This solves: MON-13188
=> Fix "last_sent" not being set when sending reports

modules/reports/models/scheduled_reports.php
The "last_sent" parameter is now being allowed to be set on the scheduled report entry in the database. 
This will fix the issue with Ninja emailing report recipients every minute.
This solves: MON-13188
=> Fix last_sent not getting set on email send

modules/reports/models/scheduled_reports.php
The check if the requested column caused a false negative when the first option was found. Embarrassing.
=> Harder false check

features/monitoring_host.feature, modules/monitoring/models/host.php, modules/monitoring/models/service.php
Set a default value "Acknowledged by <user>" if no comment is provided or setup.
This resolves MON-13222.
=> Bugfix mon13222 problem acknowledgement comment

application/views/css/layout.css, modules/monitoring/helpers/showlog.php, modules/monitoring/views/showlog/showlog.php
This commit adds a new command line option --all-nodes to the
showlog tool. This new option will gather logs from all nodes
and create a consolidated list of event logs. Each log is
appended with the node name where the log originated.
A new radio button is added to the event log page to invoke
the new  command line option.
This is part of MON-13186
Signed-off-by: Jerson Dumalaon <jdumalaon@itrsgroup.com>
=> Add --all-nodes option to showlog

application/controllers/ajax.php
This commit provides additional validation for saving icons and title to avoid xss attack via input and payload edit.
This resolves MON-13209.
=> Added icon and title validation on quicklinks

application/controllers/ajax.php
Back ported quicklink validation on title and icon details to avoid xss attacks via payload resend.
This commit resolves MON-13209.
=> Added quicklink validation to avoid xss attacks

application/views/css/layout.css, modules/menu/views/about.php
I think something went wrong when some older changes were merged.
This will introduce the old styling changes back.
=> Change styling on about page links and add divider

op5build/ci_config.yml
This commit adjusts the timezone of the test VM to Europe/Stockholm in post custom step since adjusting the timezone in PHP does not seem to handle DST.
This is part of MON-13284.
=> Workaround for DST CI failures

features/alert_history.feature, features/step_definitions/nagios.rb, modules/reports/libraries/Alert_history_options.php
This commit provides a workaround for the issue on generating the alert history. Since it is taking much time to load when it is set to 'forever', changed it to 'today' to lessen the amount of data it needs to process and load on the UI.
This resolves MON-13281
=> Change the default report period for alert history

modules/lsfilter/models/lsfilter_saved_queries.php
This commit checks if there is an existing filter name under the same username then update it instead of deleting and re-inserting the filter details. Global filters were saved will a NULL username. Global filters can have the same name as local filters. Saving a filter with the same name and scope but with different filter_table will only update the filter query.
This resolves MON-13298
=> Update filter when modified

modules/lsfilter/controllers/listview.php
A default value is set for sort variable when the query is intended for comments table. This value will only be used on initial load of the page and if the user has not selected a sorting order yet.
This should not affect other extinfo page tables that are not related to comments.
This resolves MON-10404.
=> Sets a default sort value for comments

application/views/template.php
This commit added a condition for handling lmd and naemon service status. Currently, the template only displays an error pointing that both lmd and naemon's not running.
This resolves MON-13199.
=> Updated displayed error for lmd and naemon

modules/monitoring/controllers/showlog.php
This commit sets an initial value to First Time Calendar Date as 7 days. This also removes the limit value of 2500 on initial load but will still be used if First and Last time Calendar was empty.
This resolves MON-13368
=> Sets initial value on Event Log to 7 days

application/src/js/jquery.filterable.js
Update handling for selected multiple objects
and deselecting one or more object(s) which
causes all to be unselected resulting to and
error on Availability Report. Remove function
made the same as with monitor-nacoma.
This resolves MON-13440.
Signed-off-by: Jerick Macario <jmacario@itrsgroup.com>
=> Fix handling of unselecting one or more object for Availability Report

modules/monitoring/views/extinfo/components/performance.php
Fix incomplete display of host and service page
when host is down to comprehend change of
check_icmp output from monitoring-plugins
v2.3.5 and up.
Part of MON-13431.
Signed-off-by: Jerick Macario <jmacario@itrsgroup.com>
=> Fix incomplete display of host and service page when host is down
