- features/recurring_downtime.feature
- modules/lsfilter/src/js/LSFilterList.js
- modules/monitoring/controllers/recurring_downtime.php
- modules/monitoring/models/recurringdowntime.php
- modules/monitoring/src/js/lsfilter_renderer_table.js
- modules/monitoring/views/recurring_downtime/js/recurring_downtime.js
Earlier because of recurring downtime ui changes weekdays and months is
no longer needed .
we have changed weekdays and months column to recurrence
This fixes issue MON-11414
Signed-off by Devesh Thankur dthakur@op5.com
> Ninja: Recurring downtime listview doesn't show weekdays and months.

- modules/monitoring/includes/downtime.php
- test/includes/downtime.php
This commit will change start index of weeks to 0 (sunday) to align with recent changes.
> Fix weekdays ordering

- modules/monitoring/models/recurringdowntime.php
This commit will make the list view renderer compatible with the legacy week recurrence format, i.e. single items not contained in a sequential array.
> Make list view renderer backwards compatible

- modules/menu/views/about.php
This solves MON-11593
Signed-off-by: Johan Thoren <jthoren@op5.com>
> Updated the obsolete KB link on the about page

- modules/monitoring/hooks/version_info.php
We have added OS version in about section
This fixes issue MON-11462
Signed-off by Devesh Thakur dthakur@op5.com
> "About"-frame should show RedHat version

- application/views/css/form.css
- modules/auth/views/login.php
This commit remake the style of the login page.
This ensures that the new style is applied. Add the new brand logo too.
This fixes MON-11631.
> Modify the login page styling

- application/views/css/form.css
- modules/auth/views/login.php
This commit remake the style of the login page.
This ensures that the new style is applied. Add the new brand logo too.
This fixes MON-11631.
> Modify the login page styling (#48)

- op5build/monitor-ninja.spec
This commit changes the tab name.
This ensures that the new brand name is displayed in the tab.
This is a part of MON-11626.
> Change tab name

- application/config/menu.php
- application/controllers/user.php
- application/views/template_head.php
- features/menu.feature
- modules/lsfilter/libraries/LSFilterSetBuilderVisitor.php
- test/backup_Test.php
Fixes: MON-11672
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
> Updated various links to point to our new kb instead of the old one.

- application/views/css/classic/common.css
- application/views/css/default/common.css
- application/views/css/layout.css
- application/views/css/pink_n_fluffy/common.css
Edit host form added under "Hosts and services"
Added number of unsaved changes in the save button in the menu.
CSS color changes updated.
This fixes MON-11602
Signed-off-by: Ramesh T ramesht@op5.com
> Configuration main page UI updates

- application/views/css/form.css
- modules/monitoring/views/monitoring/naemon_command.php
This commit changes the create admin account page.
This ensures that the create admin account page matches with the rebranding.
This fixes MON-11674
Signed-off-by: Adrián Villalba avillalba@itrsgroup.com
> Update create admin account

- modules/reports/models/scheduled_reports.php
timezone.
we changed the sql query to check timezone and scheduled report .
--------
Porting to 7.5, as well.
> Earlier there was some problem in generating old reports due to

- application/controllers/user.php
- application/views/css/layout.css
- application/views/template_head.php
- modules/lsfilter/libraries/LSFilterSetBuilderVisitor.php
- test/backup_Test.php
Update KB links in accordance to MON-11826
> Updated KB links

- modules/reports/models/scheduled_reports.php
This is a major re-write of the get_period_schedules() function, that
had some faults in it, causing report to not be sent or sent on the
wrong days.
This implementation should be more robust, since it doesn't rely on that
the system clock is exactly the same as the scheduled reports selected
report time.
However, this change doesn't claim to be a perfect solution to
scheduling reports.
Daily scheduled reports
-----------------------
With this change daily scheduled reports are generated as soon as
current time is beyond one report period after the report was previously
sent.
Example schedule:
- Daily report using timezone UTC
- Report time is 12:00 (same timezone as report)
- Scheduled to be sent every 2nd day
If the report was last sent anytime at 2019-10-15, it will be sent
first thing …
> Re-write cron function to get periodic schedules

- modules/reports/controllers/schedule.php
- modules/reports/models/scheduled_reports.php
Cherry-picked commits from #134
> Fix report schedules for reports with missing timezone

- modules/monitoring/models/host.php
- modules/monitoring/models/naemonobject.php
- modules/monitoring/models/service.php
Backported patch from Monitor 8.
Included is also the fix from MON-11978.
> Remove schedule downtime via API for version 7.5

- etc/auth.yml
- etc/auth_groups.yml
- install_scripts/migrate_auth.php
- src/op5/auth/Authorization.php
This commit will add a setting in group_rights that will allow users to bypass the input validation in "test_this_check", "test_this_command", etc.
> Bugfix/mon 11953 disallow command chaining in test check (#143)

- modules/lsfilter/src/js/LSFilterMultiselect.js
- modules/menu/views/menu.php
This is a rather nasty commit that hides the "Delete downtime by
hostname" functionality from both listviews and the extinfo page.
> Hide delete downtime by hostname (7.5)

- modules/lsfilter/src/js/LSFilterMultiselect.js
- modules/menu/views/menu.php
This is a rather nasty commit that hides the "Delete downtime by
hostname" functionality from both listviews and the extinfo page.
> Hide delete downtime by hostname

- etc/auth.yml
- etc/auth_groups.yml
- install_scripts/migrate_auth.php
- src/op5/auth/Authorization.php
- test/auth_files_Test.php
This will change the existing group right "allow_dangerous_characters" to 'disallow_dangerous_characters", thus making the setting opt-in for users, rather than opt-out.
> Rework test_this_check filter authentication

- application/views/css/layout.css
This commit will add an horizontal scroll bar to the lists.
This is part of MONUI-287
> MONUI-287: UI Feature request to add scroll bar in list

- application/views/css/form.css
Update font size and color for the message that is
visible on the login page if the license is expired.
Signed-off-by: Henrik Spolander <hspolander@itrsgroup.com>
> Style changes to license expired message on login

- application/views/css/default/common.css
- application/views/css/layout.css
- modules/lsfilter/views/css/LSFilterStyle.css
With this commit comes an updated style for the tables in Ninja for Monitor 9.
This a part of MONUI-862
> MONUI-862: Updated table style

- application/views/css/layout.css
- modules/auth/views/login.php
With this commit comes update to topbar, to make it work better with the new product image. Also when resizing the browser window.
This is a part of MONUI-902
> MONUI-902: Updates to topbar

- application/views/css/layout.css
With this commit we adjust the height and padding of the buttons,
to better match the inputs.
This is a part of MONUI-899
> MONUI-899: Adjust height on buttons

- features/step_definitions/nagios.rb
- modules/reports/libraries/StateCalculator.php
- modules/test/libraries/Ninja_Reports_Test.php
- src/op5/ninja_sdk/js/builder.php
- system/libraries/Input.php
This PR adds support for PHP 7.4. Please see individual commits for details.
> PHP 7.4 compatibility

- application/src/js/lib.popover.js
- modules/monitoring/controllers/pnp.php
Fixed missing error handling causing errors when so setting present.
Also added a simple caching workflow to reduce the load on the database.
This solves: MON-13048
> Fix error handling and add caching.

- application/views/css/layout.css
- modules/auth/views/login.php
Fix scaling issues of the logo on:
- Login page
- About page
This is part of: MON-13079
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>
> Correct scaling of OP5 Monitor logo

- install_scripts/ninja_db_init.sh
Make ninja_db_init.sh more robust, by not requiring it to be executed
while CWD is a specific directory.
This fixes a fault introduced in d5a5d2702, where the execution of
ninja_db_init failed to find some of it's dependent files, which
generated some install time errors like:
Could not open input file: install_scripts/upgrade_recurring_downtime.php
Fixes MON-13119.
> Make ninja_db_init.sh tolerant to CWD

- modules/monitoring/hooks/version_info.php
> Remove Naemon version from about popup

- application/src/js/application/common.js
- application/src/js/application/iframe-adjust.js
- modules/lsfilter/src/js/LSFilterSaved.js
- modules/lsfilter/src/js/lib.js
- modules/monitoring/views/recurring_downtime/js/recurring_downtime.js
- modules/reports/src/js/reports.js
Changed the way we set and get property values.
Also fixed nagvis Ipad/Android functionality.
This is part of: MON-13058
> Replace old jquery methods with new ones

- modules/reports/models/scheduled_reports.php
We now prepare the Sql query and no longer allow the user to do a
cleartext column select.
This solves: MON-13121
Signed-off-by: Axel Bolle [abolle@itrsgroup.com](mailto:abolle@itrsgroup.com)
> Fix sql injection in scheduled reports

- application/src/js/jquery.datePicker.js
The header now displays currently selected month alongside the year.
This solves: MON-13135
> Change header date display format

- application/views/template.php
- modules/monitoring/views/monitoring/naemon_command.php
This commit added handling on the monitoring module for naemon service status. Commands for checking these services status were updated for a more consistent output.
This resolve MON-13199.
> Additional Fixes for Handling Naemon and LMD Status

- Makefile
- install_scripts/nacoma_hooks.py
- op5build/monitor-ninja.spec
This commit updates the nacoma hook for Ninja to Python 3.9
This is part of MON-13334.
> Update nacoma hooks

- modules/widgets/controllers/tac.php
Fix forming of JSON response message causing
internal server error.
This resolves MON-13530.
> Fix JSON response after save

- application/views/template_head.php
Convert special characters for form parameters.
This resolves MON-13536.
> Fix XSS vulnerability

- modules/reports/controllers/reports.php
Convert special HTML entities for skin parameter.
This resolves MON-13543.
> Fix XSS finding on SLA Report
